version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-app
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
